#!/bin/bash
# ARKAN Theme — JS Bundle Builder
# Concatenates all desk JS files into a single arkan_theme.bundle.js
# This reduces 26 HTTP requests to 1.
#
# Usage: bash build_bundle.sh

set -e
cd "$(dirname "$0")"

JS_DIR="arkan_theme/public/js"
BUNDLE="$JS_DIR/arkan_theme.bundle.js"

echo "🔧 Building ARKAN desk JS bundle..."

# Order matters: arkan_theme.js (coordinator) must be first.
# Then darkmode + topbar (init early). Rest can be in any order.
FILES=(
    "$JS_DIR/arkan_theme.js"
    "$JS_DIR/arkan_darkmode.js"
    "$JS_DIR/arkan_topbar.js"
    "$JS_DIR/arkan_neural_grid.js"
    "$JS_DIR/arkan_effects.js"
    "$JS_DIR/arkan_splash.js"
    "$JS_DIR/arkan_loading.js"
    "$JS_DIR/arkan_matrix.js"
    "$JS_DIR/arkan_sounds.js"
    "$JS_DIR/arkan_workspace.js"
    "$JS_DIR/arkan_navbar.js"
    "$JS_DIR/arkan_forms.js"
    "$JS_DIR/arkan_mobile.js"
    "$JS_DIR/arkan_shortcuts.js"
    "$JS_DIR/arkan_seasons.js"
    "$JS_DIR/arkan_ambient.js"
    "$JS_DIR/arkan_cursor.js"
    "$JS_DIR/arkan_interactive_grid.js"
    "$JS_DIR/arkan_tour.js"
    "$JS_DIR/arkan_presets.js"
    "$JS_DIR/arkan_print_headers.js"
    "$JS_DIR/arkan_minigame.js"
    "$JS_DIR/arkan_animated_favicon.js"
    "$JS_DIR/arkan_pwa.js"
    "$JS_DIR/arkan_desktop.js"
    "$JS_DIR/arkan_welcome_msg.js"
)

# Build banner
cat > "$BUNDLE" << 'EOF'
// ═══════════════════════════════════════════════════════════════════
// ARKAN Theme — Bundled Desk JS
// AI & Technology Solutions — Futuristic Cyber-Tech
// Auto-generated by build_bundle.sh — DO NOT EDIT DIRECTLY
// Edit individual source files then re-run: bash build_bundle.sh
// ═══════════════════════════════════════════════════════════════════
EOF

TOTAL=0
for f in "${FILES[@]}"; do
    if [[ -f "$f" ]]; then
        echo "" >> "$BUNDLE"
        echo "// ── $(basename "$f") ──" >> "$BUNDLE"
        cat "$f" >> "$BUNDLE"
        echo "" >> "$BUNDLE"
        LINES=$(wc -l < "$f")
        TOTAL=$((TOTAL + LINES))
        echo "  ✅ $(basename "$f") ($LINES lines)"
    else
        echo "  ⚠️  MISSING: $f"
    fi
done

BUNDLE_LINES=$(wc -l < "$BUNDLE")
BUNDLE_SIZE=$(wc -c < "$BUNDLE" | xargs)

echo ""
echo "📦 Bundle created: $BUNDLE"
echo "   Source files: ${#FILES[@]}"
echo "   Total source lines: $TOTAL"
echo "   Bundle lines: $BUNDLE_LINES"
echo "   Bundle size: $BUNDLE_SIZE bytes"
echo ""

# Validate JS syntax
if command -v node &> /dev/null; then
    if node --check "$BUNDLE" 2>&1; then
        echo "✅ Bundle JS syntax: VALID"
    else
        echo "❌ Bundle JS syntax: INVALID"
        exit 1
    fi
fi

echo ""
echo "Done! Update hooks.py to load only:"
echo "  /assets/arkan_theme/js/arkan_theme.bundle.js?v=<version>"
