#!/bin/bash
# ARKAN Theme — JS Bundle Builder
# Concatenates all desk JS files into a single arkan_theme.bundle.js
# v2: Slim bundle — 14 modules removed (delegated to frappe_visual)
#
# Usage: bash build_bundle.sh

set -e
cd "$(dirname "$0")"

JS_DIR="arkan_theme/public/js"
BUNDLE="$JS_DIR/arkan_theme.bundle.js"

echo "🔧 Building ARKAN desk JS bundle (slim)..."

# Order: arkan_theme.js (coordinator) first, then fv_integration (bridge),
# then app router + media switcher, then navbar, then 3D modules, then unique brand features.
FILES=(
    "$JS_DIR/arkan_theme.js"
    "$JS_DIR/fv_integration.js"
    "$JS_DIR/arkan_app_router.js"
    "$JS_DIR/arkan_media_switcher.js"
    "$JS_DIR/arkan_navbar.js"
    "$JS_DIR/arkan_neural_grid.js"
    "$JS_DIR/arkan_splash.js"
    "$JS_DIR/arkan_splash_3d.js"
    "$JS_DIR/arkan_bg_3d.js"
    "$JS_DIR/arkan_loading_3d.js"
    "$JS_DIR/arkan_matrix.js"
    "$JS_DIR/arkan_sounds.js"
    "$JS_DIR/arkan_interactive_grid.js"
    "$JS_DIR/arkan_minigame.js"
    "$JS_DIR/arkan_animated_favicon.js"
    "$JS_DIR/arkan_pwa.js"
    "$JS_DIR/arkan_print_headers.js"
    "$JS_DIR/arkan_seasons.js"
)

# Build banner
cat > "$BUNDLE" << 'EOF'
// ═══════════════════════════════════════════════════════════════════
// ARKAN Theme — Bundled Desk JS
// AI & Technology Solutions — Futuristic Cyber-Tech
// Auto-generated by build_bundle.sh — DO NOT EDIT DIRECTLY
// Edit individual source files then re-run: bash build_bundle.sh
// ═══════════════════════════════════════════════════════════════════
EOF

TOTAL=0
for f in "${FILES[@]}"; do
    if [[ -f "$f" ]]; then
        echo "" >> "$BUNDLE"
        echo "// ── $(basename "$f") ──" >> "$BUNDLE"
        cat "$f" >> "$BUNDLE"
        echo "" >> "$BUNDLE"
        LINES=$(wc -l < "$f")
        TOTAL=$((TOTAL + LINES))
        echo "  ✅ $(basename "$f") ($LINES lines)"
    else
        echo "  ⚠️  MISSING: $f"
    fi
done

BUNDLE_LINES=$(wc -l < "$BUNDLE")
BUNDLE_SIZE=$(wc -c < "$BUNDLE" | xargs)

echo ""
echo "📦 Bundle created: $BUNDLE"
echo "   Source files: ${#FILES[@]}"
echo "   Total source lines: $TOTAL"
echo "   Bundle lines: $BUNDLE_LINES"
echo "   Bundle size: $BUNDLE_SIZE bytes"
echo ""

# Validate JS syntax
if command -v node &> /dev/null; then
    if node --check "$BUNDLE" 2>&1; then
        echo "✅ Bundle JS syntax: VALID"
    else
        echo "❌ Bundle JS syntax: INVALID"
        exit 1
    fi
fi

echo ""
echo "Done! Update hooks.py to load only:"
echo "  /assets/arkan_theme/js/arkan_theme.bundle.js?v=<version>"
